version = 1
SPDX-PackageName = "cklabScheduler"
SPDX-PackageSupplier = "Pexip AS"
SPDX-PackageDownloadLocation = "https://github.com/pexip-labs/cklabScheduler"

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Pexip AS"
SPDX-License-Identifier = "Apache-2.0"
